### ISSUE TITLE
Excuse me, where is it better to download the Mode made by others;

### ISSUE THREAD

**Issue by tlerbao** [HighTechLowIQ/ModdingDiablo2Resurrected#1]
Excuse me, where is it better to download the Mode made by others;

**Comment by HighTechLowIQ** [comment]
You can download mods in several places, the main ones being:

[Nexus Mods](https://www.nexusmods.com/diablo2resurrected/mods/)
[ModDB](https://www.moddb.com/games/diablo-ii-resurrected)
