### ISSUE TITLE
[Help] List item mod

### ISSUE THREAD

**Issue by qhu91it** [HighTechLowIQ/ModdingDiablo2Resurrected#4]
Do you have list item mod name and prefix? like dmg = Enhanced Damage, ac = Enhanced Defense, regen-mana = Regenerate Mana...
I have searching for mod name "Requirements" but doesn't know that prefix

**Comment by HighTechLowIQ** [comment]
You can check out the properties.txt for a list of the properties and their codes.

-Requirements% is row 77 - "ease".
