### ISSUE TITLE
Еxtraction of specific language

### ISSUE THREAD

**Issue by Hellioob** [HighTechLowIQ/ModdingDiablo2Resurrected#5]
Hello,

Is there a way to extract a specific language (example: ruRU) and after edited then return it back to file?

Thanks!

**Comment by HighTechLowIQ** [comment]
Those languages are available under the locales directory, and you could pack them back into [an MPQ](https://www.youtube.com/watch?v=tLMppJOOO0o) file, or a [mod directory](https://www.youtube.com/watch?v=lZTTq7MXZ5w), but I think there are currently problems with modding different locales, [according to this comment thread on Phrozen Keep](https://d2mods.info/forum/viewtopic.php?f=217&t=67508&sid=b553b136be722905c1f20dd3067d7183).
